# Generated by Django 4.1.4 on 2022-12-31 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_level_grade_alter_profile_grade_alter_profile_level'),
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, upload_to='teacher/posts')),
                ('disc', models.TextField(max_length=1000, null=True)),
                ('link1', models.URLField(blank=True)),
                ('link2', models.URLField(blank=True)),
                ('link3', models.URLField(blank=True)),
                ('file1', models.FileField(blank=True, upload_to='teacher/posts')),
                ('file2', models.FileField(blank=True, upload_to='teacher/posts')),
                ('file3', models.FileField(blank=True, upload_to='teacher/posts')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('for_grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.grade')),
                ('teacher', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='teacher.teacher')),
            ],
        ),
    ]
