# Generated by Django 4.1.4 on 2022-12-31 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_subject_teacher_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gradepost',
            name='image',
        ),
    ]
