# Generated by Django 4.1.4 on 2023-01-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_library_author_library_disc'),
        ('teacher', '0005_teacher_first_name_teacher_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='subscribers',
            field=models.ManyToManyField(to='student.student'),
        ),
    ]
