# Generated by Django 4.1.4 on 2023-01-02 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0006_teacher_subscribers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subject',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(to='teacher.subject'),
        ),
    ]
