# Generated by Django 4.1.4 on 2023-01-02 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0017_library_author_library_disc'),
        ('teacher', '0007_remove_teacher_subject_teacher_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='subject',
            field=models.ManyToManyField(related_name='teacher_subjects', to='teacher.subject'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='subscribers',
            field=models.ManyToManyField(related_name='teacher_Subscribers', to='student.student'),
        ),
    ]
