# Generated by Django 4.1.5 on 2023-01-09 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_profile_grade'),
        ('teacher', '0012_teacher_facebook'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='my_room',
            field=models.ManyToManyField(to='home.grade'),
        ),
    ]
