# Generated by Django 4.1.5 on 2023-01-09 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0046_alter_profile_grade'),
        ('teacher', '0013_teacher_my_room'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='my_room',
        ),
        migrations.AddField(
            model_name='teacher',
            name='my_room',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.grade'),
        ),
    ]
