# Generated by Django 4.1.5 on 2023-01-21 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_alter_profile_level'),
        ('teacher', '0018_teacher_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='grade',
        ),
        migrations.AddField(
            model_name='subject',
            name='grade',
            field=models.ManyToManyField(to='home.grade'),
        ),
    ]
