# Generated by Django 4.1.5 on 2023-01-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0020_remove_subject_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='detail',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
