# Generated by Django 4.1.5 on 2023-02-06 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0023_homeroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='homeroom',
            name='year',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
