# Generated by Django 4.1.5 on 2023-02-10 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0025_cardtype'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtype',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
