# Generated by Django 4.1.5 on 2023-02-10 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0028_cardtype_padding'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtype',
            name='border',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='borderColor',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='bottom',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='height',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='left',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='padding',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='right',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='top',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='type',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='width',
        ),
        migrations.AddField(
            model_name='cardtype',
            name='box',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='sc_icon',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='sc_info',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='st_grade',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='st_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cardtype',
            name='table',
            field=models.BooleanField(default=True),
        ),
    ]
