# Generated by Django 4.1.5 on 2023-02-11 05:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0029_remove_cardtype_border_remove_cardtype_bordercolor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='cardTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.cardtype')),
            ],
        ),
    ]
