# Generated by Django 4.1.5 on 2023-02-16 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0031_cardtable_border_cardtable_height_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='cardTable',
            new_name='CTable',
        ),
    ]
