# Generated by Django 4.1.5 on 2023-02-18 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0032_rename_cardtable_ctable'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cardtype',
            name='box',
        ),
        migrations.RemoveField(
            model_name='cardtype',
            name='sc_info',
        ),
    ]
