# Generated by Django 4.1.5 on 2023-02-18 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0033_remove_cardtype_box_remove_cardtype_sc_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
                ('text', models.TextField(max_length=5000, null=True)),
                ('line', models.BooleanField(default=False)),
                ('width', models.FloatField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True)),
                ('y_axis', models.FloatField(blank=True, null=True)),
                ('x_axis', models.FloatField(blank=True, null=True)),
                ('text_size', models.FloatField(blank=True, null=True)),
                ('text_font', models.CharField(blank=True, max_length=2555, null=True)),
                ('line_width', models.FloatField(blank=True, null=True)),
                ('line_y_axis', models.FloatField(blank=True, null=True)),
                ('line_x_axis', models.FloatField(blank=True, null=True)),
                ('cardTable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.cardtype')),
            ],
        ),
    ]
