# Generated by Django 4.1.5 on 2023-02-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0037_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='line',
            name='name',
            field=models.IntegerField(null=True),
        ),
    ]
