# Generated by Django 4.1.5 on 2023-02-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0038_alter_line_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ctable',
            name='border',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
