# Generated by Django 4.1.5 on 2023-04-20 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0040_alter_ctable_height_alter_ctable_name_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtype',
            name='bi',
            field=models.BooleanField(default=False),
        ),
    ]
