# Generated by Django 4.1.5 on 2023-06-20 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='verify_user',
            field=models.BooleanField(default=False),
        ),
    ]
