# Generated by Django 4.1.5 on 2023-06-20 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_staff_verify_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='modify_student',
            field=models.BooleanField(default=False),
        ),
    ]
