# Generated by Django 4.1.5 on 2023-06-20 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0003_staff_modify_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='transfer',
            field=models.BooleanField(default=False),
        ),
    ]
