# Generated by Django 4.1.5 on 2023-06-21 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0005_alter_staff_modify_student_alter_staff_report_card_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='time',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staff',
            name='transfer',
            field=models.BooleanField(default=False),
        ),
    ]
