# Generated by Django 4.1.4 on 2023-01-05 11:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0012_teacher_facebook'),
        ('redirector', '0003_delete_resulthistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResultHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField()),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redirector.history')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redirector.testhistory')),
                ('subjects', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.subject')),
            ],
        ),
    ]
