# Generated by Django 4.1.4 on 2023-01-05 13:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0004_resulthistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ResultHistory',
        ),
    ]
