# Generated by Django 4.1.5 on 2023-01-13 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0006_alter_academicyear_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academicyear',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
