# Generated by Django 4.1.5 on 2023-01-13 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0007_alter_academicyear_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='password',
        ),
    ]
