# Generated by Django 4.1.5 on 2023-01-13 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0008_remove_history_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='testhistory',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
