# Generated by Django 4.1.5 on 2023-01-13 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0009_testhistory_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='testhistory',
            name='academicYear',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='redirector.academicyear'),
        ),
    ]
