# Generated by Django 4.1.5 on 2023-06-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0012_academicyear_new'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicyear',
            name='start',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
