# Generated by Django 4.1.4 on 2022-12-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_mainpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpack',
            name='slogan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
