# Generated by Django 4.1.4 on 2022-12-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_webpack_slogan'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpack',
            name='app',
            field=models.FileField(blank=True, null=True, upload_to='webpack/'),
        ),
    ]
