# Generated by Django 4.1.4 on 2022-12-24 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_webpack_app'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpack',
            name='about',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
