# Generated by Django 4.1.4 on 2022-12-24 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_webpack_about'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpack',
            name='registration_deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='webpack',
            name='registration_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
