# Generated by Django 4.1.4 on 2022-12-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_webpack_registration_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webpack',
            name='registration_deadline',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='webpack',
            name='registration_start',
            field=models.DateField(blank=True, null=True),
        ),
    ]
