# Generated by Django 4.1.4 on 2022-12-24 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_alter_webpack_registration_deadline_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webpack',
            name='registration_start',
        ),
        migrations.AddField(
            model_name='webpack',
            name='show_register',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
