# Generated by Django 4.1.4 on 2022-12-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_webpack_registration_start_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('cover', models.ImageField(upload_to='anonymous/blog/')),
            ],
        ),
        migrations.AlterField(
            model_name='mainpage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='anonymous/webpack/'),
        ),
        migrations.AlterField(
            model_name='webpack',
            name='app',
            field=models.FileField(blank=True, null=True, upload_to='anonymous/webpack/'),
        ),
        migrations.AlterField(
            model_name='webpack',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='anonymous/webpack/'),
        ),
    ]
