# Generated by Django 4.1.4 on 2022-12-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='webpack',
            name='facebook',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='webpack',
            name='telegram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
