# Generated by Django 4.1.4 on 2022-12-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_webpack_theme_color'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='anonymous/about/')),
                ('paragraph', models.TextField(blank=True, max_length=2555, null=True)),
            ],
        ),
    ]
