# Generated by Django 4.1.4 on 2022-12-24 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_blog_p1_blog_p2_blog_p3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='anonymous/blog/'),
        ),
        migrations.CreateModel(
            name='Addblog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='anonymous/blog/')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('p1', models.TextField(blank=True, max_length=5000, null=True)),
                ('p2', models.TextField(blank=True, max_length=5000, null=True)),
                ('p3', models.TextField(blank=True, max_length=5000, null=True)),
                ('blog', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.blog')),
            ],
        ),
    ]
