# Generated by Django 4.1.4 on 2022-12-24 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='home.event'),
        ),
    ]
