# Generated by Django 4.1.4 on 2022-12-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_gallery_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='on_front',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
