# Generated by Django 4.1.4 on 2022-12-25 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_password'),
    ]

    operations = [
        migrations.RenameField(
            model_name='password',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='password',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
