# Generated by Django 4.1.4 on 2022-12-25 10:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0027_password_phone_password_sex'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=255, null=True)),
                ('sex', models.CharField(max_length=255, null=True)),
                ('level', models.CharField(max_length=255, null=True)),
                ('grade', models.CharField(max_length=255, null=True)),
                ('is_manager', models.BooleanField(default=False, null=True)),
                ('is_teacher', models.BooleanField(default=False, null=True)),
                ('is_student', models.BooleanField(default=True, null=True)),
                ('is_staff', models.BooleanField(default=False, null=True)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
