# Generated by Django 4.1.4 on 2022-12-26 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0029_profile_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='password',
            name='password',
        ),
        migrations.AddField(
            model_name='password',
            name='of',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_password', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='password',
            name='passwords',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
