# Generated by Django 4.1.4 on 2022-12-31 07:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_rename_passwords_password_password_alter_password_of'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.event'),
        ),
    ]
