# Generated by Django 4.1.4 on 2022-12-31 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_remove_profile_grade_remove_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.grade'),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.level'),
        ),
    ]
