# Generated by Django 4.1.4 on 2022-12-31 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_profile_grade_profile_level'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='grade',
            new_name='grades',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='level',
            new_name='levels',
        ),
    ]
