# Generated by Django 4.1.4 on 2022-12-31 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0037_rename_grade_profile_grades_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='grades',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='levels',
        ),
    ]
