# Generated by Django 4.1.4 on 2022-12-31 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0038_remove_profile_grades_remove_profile_levels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Level',
            new_name='Levels',
        ),
    ]
