# Generated by Django 4.1.4 on 2022-12-31 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0039_rename_level_levels'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Levels',
            new_name='Campas',
        ),
    ]
