# Generated by Django 4.1.4 on 2022-12-31 09:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0040_rename_levels_campas'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='grade',
            name='level',
        ),
        migrations.DeleteModel(
            name='Campas',
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
    ]
