# Generated by Django 4.1.4 on 2022-12-31 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0041_remove_grade_level_delete_campas_delete_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
