# Generated by Django 4.1.4 on 2022-12-31 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0042_profile_grade_profile_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='level',
        ),
    ]
