# Generated by Django 4.1.4 on 2022-12-31 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0043_remove_profile_grade_remove_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='level',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
