# Generated by Django 4.1.5 on 2023-03-20 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_alter_profile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='new',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
