# Generated by Django 4.1.5 on 2023-04-11 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0051_profile_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='new',
        ),
    ]
