# Generated by Django 4.1.4 on 2022-12-26 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='instagram',
            field=models.CharField(blank=True, max_length=5255, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='telegram',
            field=models.CharField(blank=True, max_length=5255, null=True),
        ),
    ]
