# Generated by Django 4.1.4 on 2022-12-26 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_student_instagram_student_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='template',
            field=models.ImageField(blank=True, null=True, upload_to='student/profile/'),
        ),
    ]
