# Generated by Django 4.1.4 on 2022-12-31 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_student_template'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='template',
        ),
    ]
