# Generated by Django 4.1.4 on 2023-01-01 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_chat_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='code',
        ),
        migrations.CreateModel(
            name='chatCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=255, null=True)),
                ('to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='student.chat')),
            ],
        ),
    ]
