# Generated by Django 4.1.4 on 2023-01-01 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0013_student_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='reciever',
        ),
        migrations.AddField(
            model_name='student',
            name='view',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='student.student'),
        ),
    ]
