# Generated by Django 4.1.4 on 2023-01-02 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0015_library'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='library',
            name='for_all',
        ),
    ]
