# Generated by Django 4.1.4 on 2023-01-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0016_remove_library_for_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='author',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='library',
            name='disc',
            field=models.TextField(max_length=2555, null=True),
        ),
    ]
