# Generated by Django 4.1.4 on 2023-01-02 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_level_grade_alter_profile_grade_alter_profile_level'),
        ('student', '0019_course_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='views',
            field=models.ManyToManyField(to='home.profile'),
        ),
    ]
