# Generated by Django 4.1.4 on 2023-01-03 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0024_alter_course_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
