# Generated by Django 4.1.4 on 2023-01-04 05:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0023_remove_course_views_coursecomment_course_views'),
        ('student', '0025_alter_course_views'),
    ]

    operations = [
    ]
