# Generated by Django 4.1.4 on 2023-01-04 05:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0026_merge_20230104_0845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='views',
        ),
    ]
