# Generated by Django 4.1.4 on 2023-01-04 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0032_remove_result_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='section',
        ),
    ]
