# Generated by Django 4.1.4 on 2023-01-04 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0001_initial'),
        ('student', '0033_remove_student_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='redirector.academicyear'),
        ),
    ]
