# Generated by Django 4.1.5 on 2023-01-09 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0038_student_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='average',
            field=models.IntegerField(null=True),
        ),
    ]
