# Generated by Django 4.1.5 on 2023-01-10 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0039_student_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='author',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
