# Generated by Django 4.1.5 on 2023-01-10 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0042_remove_test_time_result_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='time',
            field=models.CharField(choices=[('first academic term', 'first academic term'), ('second academic term', 'second academic term')], max_length=255, null=True),
        ),
    ]
