# Generated by Django 4.1.5 on 2023-01-12 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0005_delete_resulthistory'),
        ('student', '0043_test_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='redirector.academicyear'),
        ),
        migrations.AlterField(
            model_name='student',
            name='view',
            field=models.BooleanField(default=True),
        ),
    ]
