# Generated by Django 4.1.5 on 2023-01-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0044_test_year_alter_student_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='average',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
