# Generated by Django 4.1.5 on 2023-01-13 18:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0005_delete_resulthistory'),
        ('student', '0045_alter_student_average'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='redirector.academicyear'),
        ),
    ]
