# Generated by Django 4.1.5 on 2023-01-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0046_alter_student_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='resulthistory',
            name='time',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
