# Generated by Django 4.1.5 on 2023-01-17 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0010_testhistory_academicyear'),
        ('student', '0049_subjectreslut'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectreslut',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='redirector.academicyear'),
        ),
    ]
