# Generated by Django 4.1.5 on 2023-01-17 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0050_subjectreslut_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectreslut',
            name='time',
            field=models.CharField(choices=[('first academic term', 'first academic term'), ('second academic term', 'second academic term')], max_length=255, null=True),
        ),
    ]
