# Generated by Django 4.1.5 on 2023-01-17 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_alter_profile_level'),
        ('student', '0052_remove_subjectreslut_status_subjectreslut_first_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectreslut',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.grade'),
        ),
    ]
