# Generated by Django 4.1.5 on 2023-01-18 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0010_testhistory_academicyear'),
        ('student', '0054_studentstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstatus',
            name='time',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='redirector.academicyear'),
        ),
    ]
