# Generated by Django 4.1.5 on 2023-01-18 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0055_studentstatus_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentstatus',
            name='first_rank',
        ),
        migrations.RemoveField(
            model_name='studentstatus',
            name='second_rank',
        ),
        migrations.AddField(
            model_name='studentstatus',
            name='average',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='studentstatus',
            name='first_from',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentstatus',
            name='first_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentstatus',
            name='second_from',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='studentstatus',
            name='second_total',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentstatus',
            name='first_average',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='studentstatus',
            name='second_average',
            field=models.FloatField(null=True),
        ),
    ]
