# Generated by Django 4.1.5 on 2023-01-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0057_studentstatus_first_rank_studentstatus_rank_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectreslut',
            name='first_from',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subjectreslut',
            name='second_from',
            field=models.IntegerField(null=True),
        ),
    ]
