# Generated by Django 4.1.5 on 2023-01-19 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0058_subjectreslut_first_from_subjectreslut_second_from'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjectreslut',
            old_name='first_from',
            new_name='f_from',
        ),
        migrations.RemoveField(
            model_name='subjectreslut',
            name='second_from',
        ),
    ]
