# Generated by Django 4.1.5 on 2023-01-19 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0059_rename_first_from_subjectreslut_f_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectreslut',
            name='s_from',
            field=models.IntegerField(null=True),
        ),
    ]
