# Generated by Django 4.1.5 on 2023-01-23 07:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0011_subjectresluthistory_studentstatushistory'),
        ('student', '0061_remove_test_grade_test_grade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resulthistory',
            name='date',
        ),
        migrations.AddField(
            model_name='resulthistory',
            name='year',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='redirector.academicyear'),
        ),
    ]
