# Generated by Django 4.1.5 on 2023-02-08 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0063_test_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectreslut',
            name='year',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
