# Generated by Django 4.1.5 on 2023-02-08 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0064_subjectreslut_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentstatus',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
