# Generated by Django 4.1.5 on 2023-02-08 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0065_studentstatus_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjectreslut',
            name='f_rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subjectreslut',
            name='rank',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='subjectreslut',
            name='s_rank',
            field=models.IntegerField(null=True),
        ),
    ]
