# Generated by Django 4.1.5 on 2023-02-08 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0050_alter_profile_level'),
        ('student', '0067_remove_subjectreslut_f_rank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentstatus',
            name='grade',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.grade'),
        ),
    ]
