# Generated by Django 4.1.5 on 2023-02-26 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0068_alter_studentstatus_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='full_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
