# Generated by Django 4.1.5 on 2023-04-11 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0070_alter_student_full_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='new',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
