# Generated by Django 4.1.5 on 2023-04-20 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('redirector', '0011_subjectresluthistory_studentstatushistory'),
        ('teacher', '0041_cardtype_bi'),
        ('student', '0071_student_new'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='redirector.history')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teacher.cardtype')),
            ],
        ),
    ]
