# Generated by Django 4.1.5 on 2023-04-21 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0072_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Time',
        ),
    ]
