# Generated by Django 4.1.4 on 2022-12-31 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0045_level_grade_alter_profile_grade_alter_profile_level'),
        ('manager', '0004_studentmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmessage',
            name='for_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentmessage',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.grade'),
        ),
    ]
