# Generated by Django 4.1.4 on 2022-12-31 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0006_remove_studentmessage_for_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmessage',
            name='for_all',
            field=models.BooleanField(default=False),
        ),
    ]
