# Generated by Django 4.1.4 on 2022-12-31 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0007_studentmessage_for_all'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmessage',
            name='for_all',
        ),
    ]
