# Generated by Django 4.1.4 on 2022-12-31 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0008_remove_studentmessage_for_all'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmessage',
            name='link',
            field=models.CharField(blank=True, max_length=2555),
        ),
    ]
