# Generated by Django 4.1.4 on 2023-01-01 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0010_studentmessage_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='manager',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
