# Generated by Django 4.1.5 on 2023-01-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0011_manager_first_name_manager_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='city',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='nationality',
        ),
    ]
