# Generated by Django 4.1.5 on 2023-01-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0012_remove_manager_city_remove_manager_nationality'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
